# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-16 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projectComment',
            field=models.TextField(default='', max_length=200, verbose_name='专家项目评语'),
        ),
        migrations.AddField(
            model_name='projects',
            name='projectLeader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='项目负责人'),
        ),
        migrations.AddField(
            model_name='projects',
            name='projectUnit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='项目单位'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectDesc',
            field=models.TextField(default='', max_length=200, verbose_name='项目简介'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectName',
            field=models.CharField(help_text='项目名称', max_length=50, verbose_name='项目名称'),
        ),
    ]
