# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-18 06:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missions',
            name='id',
        ),
        migrations.AddField(
            model_name='missions',
            name='missionLeader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderMission', to=settings.AUTH_USER_MODEL, verbose_name='任务负责人'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='missionId',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='项目编号'),
        ),
    ]
